### ISSUE TITLE
리방시에 녹화 재개가 안되는 문제

### ISSUE THREAD

**Issue by jamcat10** [munsy0227/Chzzk-Rekoda#1]
리눅스 버전이 필요했는데 덕분에 잘 쓰고 있습니다.
스트리머가 리방시에 녹화 재개가 안되고 해당 스트리머는 더 이상 녹화가 진행이 안되는 문제가 발생하는데 검토해주시면 감사하겠습니다.

**Comment by munsy0227** [comment]
오늘 그냥 코드를 갈아엎었는데 한번 확인해 주술 수 있나요? 
제가 시간이 없어서 테스트하기가 힘들 거 같네요
만약에 오류가 발생한 다면 에러를 복붙해서 적어주세요

**Comment by munsy0227** [comment]
Exception in thread Thread-2 (record_stream):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/NASLoad/NAS/Chzzk-Auto-Recorder-for-Linux/chzzk_record.py", line 82, in
 record_stream
    stream_url = json.loads(live_info.get("livePlaybackJson") or "{}").get("medi
a", [{}])[0].get("path", "")
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~^^^
IndexError: list index out of range 
에러가 이런가요?

**Comment by jamcat10** [comment]
백그라운드로 돌리고 있고 로그를 남기지 않아서 정확히 재현은 힘든 것 같습니다.
아래는 원본 링크의 개발자분이 남기신 댓글입니다.

> Q : 0.8c 쓰는데 자동녹화 돌려놓고 잤다가 오니까 새벽에 시로 방송 리방 후부터 녹화가 안돼있습니다 프롬프트에는 아예 마시로 탐색이 중지돼있고 GUI에는 녹화 중 이라고 뜨는데 실제 파일은 리방 전 6분짜리 영상만 남아있고 리방 후 파일은 녹화가 없네요 일어나서 녹화 중지 후 다시 시작하니까 탐색은 다시 시작했는데 버그 발생 조건은 잘 모르겠네요 다른 스트리머 녹화할때는 리방하거나 방송 끊겼을때도 끊기기 전이랑 리방 후 영상 둘 다 잘 녹화댔었는데...
> 
> A : 원인을 발견하였습니다. 간단하게 스머가 방송종료하면 치지직 서버에서 OPEN -> CLOSE 되는 것을 확인하는 텀이 약 10~30초 정도됩니다. 미디어 방송화면은 종료되어 "녹화 종료" 를 인식했지만. 치지직에서 OPEN -> CLOSE 된 것을 재확인하는 방식이 딜레이가 생기면서, 10~30초 텀 사이에 자동예약녹화 루틴과 겹쳐 녹화 재시도를 여러번 하게됩니다. 3~4번 시도하다 안되면 오류를 내뱉는데 해당 오류때문에 예약녹화로 넘어가지 못하는게 문제였습니다.
> 
> 자도 예약녹화 불가 + 방송종료 꼬리 파편화 파일 2~3개 생기는 원인이 이거였고 일단 오늘 내일 수정을 시도해보겠습니다.

**Comment by jamcat10** [comment]
오늘 업데이트 후에 이런 오류가 발생합니다.

Traceback (most recent call last):
  File "/Chzzk-Auto-Recorder-for-Linux/chzzk_record.py", line 173, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Chzzk-Auto-Recorder-for-Linux/chzzk_record.py", line 168, in main
    await asyncio.gather(*tasks, *monitor_tasks)
  File "/Chzzk-Auto-Recorder-for-Linux/chzzk_record.py", line 154, in monitor_stream_url
    stream_url = await fetch_stream_url(channel, headers)
  File "/Chzzk-Auto-Recorder-for-Linux/chzzk_record.py", line 80, in fetch_stream_url
    live_playback_json = json.loads(live_info.get("livePlaybackJson") or "{}").get("media", [])
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by munsy0227** [comment]
현재는 별문제 없으신가요? 제가 리방 테스트를 할 여건이 안되어서 문제가 있는지 확인이 불가능하네요

**Comment by jamcat10** [comment]
리방 후 랜덤으로 녹화가 안되는 문제는 여전히 발생하고 있습니다 ㅠ

**Comment by munsy0227** [comment]
"방송종료 꼬리 파편화 파일 2~3개 생기는 원인" 이걸 이제 봤네요. 이 문제 해결하면 문제없어질 거 같네요.

**Comment by jamcat10** [comment]
파편화 파일은 없어진 것 같지만 리방후에 녹화 안되는 문제는 그대로 발생합니다.

**Comment by jamcat10** [comment]
3월 9일 업데이트 후부터 녹화가 중간에 끊겨버리는 문제가 발생합니다. 예를 들어 파일이 8시간 길이인데 실제 용량은 훨씬 못미치고 특정 부분 이후부터 재생이 안되는 문제가 발생합니다.

**Comment by munsy0227** [comment]
혹시 해결되었나요?

**Comment by jamcat10** [comment]
녹화 끊가는 건 치지직 서버쪽 문제인 것 같아 vpn을 키는 걸로 해결 보았습니다. 다만 업데이트 후에  꼬리 파편화 파일이 이젠 3개씩 생기네요 ㅠ (아직 이번 업데이트는 적용하지 않았습니다)

**Comment by munsy0227** [comment]
꼬리 파편화 파일은 치지직의 api 갱신 주기가 느려서 어쩔 수 없는 거로 알고 있어요
그리고 리방 문제가 해결됐으니까 이 이슈는 끝내는 거로 할게요
