### ISSUE TITLE
마지막 세팅을 할때 저장경로에 뭘 입력해야하나요?

### ISSUE THREAD

**Issue by apppeter1** [munsy0227/Chzzk-Rekoda#20]
![AlyacM_Screenshot_20241018-124036](https://github.com/user-attachments/assets/ace2e10b-80d6-471d-8ffe-976231e82e9a)
안녕하세요 혹시 여기서 storage path에 뭘 입력해야하는지 도움을 받을 수 있을까요?

**Comment by munsy0227** [comment]
저기에 "러너"를 입력하시면, Chzzk-Rekoda 폴더 내에 ‘러너’라는 폴더가 새롭게 생성되며, 해당 폴더에 파일이 저장됩니다.
그리고, 디렉토리 경로를 ‘~/러너’와 같이 입력하시면, 녹화된 영상이 그 경로에 저장됩니다.

**Comment by apppeter1** [comment]
친절한 설명 감사합니다

**Comment by apppeter1** [comment]
![AlyacM_Screenshot_20241018-224208](https://github.com/user-attachments/assets/2244c1c9-5d7e-4250-94b5-7598933f2ede)
죄송한데 혹시 이렇게 뜨는데 제가 런칭을 잘못한게 있을까요?

**Comment by munsy0227** [comment]
"Y"를 입력한 후, 엔터 키를 누르시면 됩니다.

**Comment by apppeter1** [comment]
늦은시간에 답변해주셔서 감사합니다!!

**Comment by munsy0227** [comment]
방금 문제가 해결되었습니다

**Comment by apppeter1** [comment]
아 넵 감사합니다!!

**Comment by apppeter1** [comment]
어제 잘못 녹화된 파일이 있어서 am start -a android.intent.action.VIEW -d "content://com.android.externalstorage.documents/root/primary" 명령어를 사용했는데 연란처가 열리는게 정상인가요? 밑에 명령어로는 파일이 안지워지더라구요

**Comment by apppeter1** [comment]
혹시 위에서 물어본 파일 지우는 법은 없나요?

**Comment by munsy0227** [comment]
Discussions에 airincast님께 물어보시죠. 저는 termux는 아예 몰라서
