### ISSUE TITLE
huge .log file size

### ISSUE THREAD

**Issue by challi1337** [munsy0227/Chzzk-Rekoda#23]
I'm running the program in a docker container unattended and after a few days of recording the .log file in the folder is huge.

Picture is after 5 days
![image](https://github.com/user-attachments/assets/67806257-98f4-40df-b891-02bae7fbbd89)

**Comment by munsy0227** [comment]
I was aware of this issue early in the development as well, but I left it unattended by simply deleting it periodically. Therefore, I plan to improve the logging functionality when I have time.

**Comment by scweeny** [comment]
![이미지2163](https://github.com/user-attachments/assets/5ea81376-8628-422f-a572-fdf7a812d137)
As a temporary measure, I commented out these four lines inside the chzzk_record.py file.
Because I don't need log files anyway.
