### ISSUE TITLE
로그 파일로 저장 옵션 유무가 가능했으면 좋겠습니다

### ISSUE THREAD

**Issue by jamcat10** [munsy0227/Chzzk-Rekoda#24]
개인적으로 꽤 많은 스트리머를 동시에 녹화하는데 때문에 로그 파일 크기가 며칠만 지나도 몇 십기가가 되버려서 곤란한 상황이 발생합니다.
옵션에서 로그 파일 저장 유무를 키고 끌 수 있었으면 좋겠습니다.
늘 잘쓰고 있습니다. 감사합니다.

**Comment by starft8900** [comment]
해당 기능이 추가되기 전까지 윈도우 사용자시면 powershell에서 clear-content .\경로\log.log로 로그파일 clear 가능합니다.

**Comment by munsy0227** [comment]
https://github.com/munsy0227/Chzzk-Rekoda/commit/0fbdac6729211e0859655c3bda03e7c935510fdc
기능 추가했습니다. 곧 업데이트 될 예정이예요.
