### ISSUE TITLE
[라즈베리파이OS 구동확인] 고맙읍니다

### ISSUE THREAD

**Issue by asdf916** [munsy0227/Chzzk-Rekoda#3]
사실 이슈는 아니구요,,, 원래 라즈베리파이로 자동녹화머신 돌리고 있었는데
많이 사용하는 '내맘대로 치지직chzzk 자동녹화'는 (리눅스는 모르겠지만) 라즈베리에선 플러그인 에러 뱉으면서 안 되더라구요ㅠㅠ
그런데 선생님이 맨들어주신 이거 쓰니까 잘 됐읍니다 고맙읍니다ㅠㅠ

**Comment by munsy0227** [comment]
사용해 주셔서 감사합니다
