### ISSUE TITLE
윈도우 bat 화면관련 건의사항입니다

### ISSUE THREAD

**Issue by scweeny** [munsy0227/Chzzk-Rekoda#7]
![이미지1223](https://github.com/munsy0227/Chzzk-Rekoda/assets/6022156/101260a9-524a-401a-9a72-22a1ab3bbaae)

에러는 간단하게 표시하고..

녹화중인 것의 상세정보를 표시하는게 낫지 않을까 생각됩니다.

녹화중인 파일을 확인 전까지는 녹화가 되는지 안되는지 잘 모르겠더라고요

**Comment by munsy0227** [comment]
조금 전에 코드 수정했는데 원하시는 대로 되었는지 확인 부탁드립니다

**Comment by scweeny** [comment]
> 조금 전에 코드 수정했는데 원하시는 대로 되었는지 확인 부탁드립니다

감사합니다. 잘되는거 확인했습니다 고생많으십니다 ㅠㅠ
